# Generated by Django 4.0.4 on 2022-04-20 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='sellers.seller'),
            preserve_default=False,
        ),
    ]
