version: "3.8"

services:
    postgres:
        image: postgres:13.4-alpine
        restart: always
        env_file: .env
        ports:
            - 5433:5432
    django:
        build:
            context: ../
            dockerfile: compose/Dockerfile
            args:
                - USER_ID=1000
                - GROUP_ID=1000
                - REQUIREMENTS_FILE=requirements.dev.txt
            target: dev # FROM builder as dev
        volumes:
            - ../src:/app
        restart: always
        env_file: .env
        environment:
            DJANGO_DEBUG: 'true'
        command: /entrypoint
        ports:
            - "8000:8000" # "8000-8500:8000" # PORT RANGE TO SCALE
        depends_on:
            - postgres
        stdin_open: true
        tty: true
