# Generated by Django 4.0.4 on 2022-04-16 18:23

from django.db import migrations, models
import django.db.models.deletion
import sellers.models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_product_description_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=sellers.models.upload_gallery_image)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sellers.product')),
            ],
        ),
    ]
